#! /bin/bash

for f in ~/scripts/*; do source $f; done

alias faye="bundle exec rackup private_pub.ru -s thin -E production"
alias droplet='ssh karin@104.131.162.130 -A'
alias find_error_number="find app/assets/javascripts/ -type f -exec sed -E -n -e 's/.*alert\(.*\(([0-9][0-9]?)\).*/\1/p' {} \; | sort -n"
alias say='say -v Karen'
alias find_listeners='lsof -i | grep LISTEN'
alias ls='ls -a'
